/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#002550",
        "primary-container": "#123b70",
        "on-primary": "#ffffff",
        "on-primary-container": "#85a7e2",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary-fixed": "#001b3e",
        "on-primary-fixed-variant": "#21477c",
        "inverse-primary": "#a9c7ff",

        secondary: "#994700",
        "secondary-container": "#ff8429",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#632c00",
        "secondary-fixed": "#ffdbc8",
        "secondary-fixed-dim": "#ffb68b",
        "on-secondary-fixed": "#321300",
        "on-secondary-fixed-variant": "#743400",

        tertiary: "#242628",
        "tertiary-container": "#393c3e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a4a6a8",
        "tertiary-fixed": "#e1e2e4",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        background: "#fcf9f8",
        "on-background": "#1b1c1c",
        surface: "#fcf9f8",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#43474f",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",

        outline: "#737780",
        "outline-variant": "#c3c6d1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "surface-tint": "#3c5f96",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        xxl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "8px",
        md: "16px",
        lg: "24px",
        gutter: "24px",
        xl: "40px",
        xxl: "80px",
        "margin-mobile": "20px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        caption: ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
